AppFinal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('TravelBook.urls')),
    path('account/',include('account.urls')),
    path('weather/',include('Weth_Ne.urls')),


]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

TravelBook/urls.py
from django.urls import path
from . import views

app_name = 'Booking'
urlpatterns = [

    path('', views.index,name='index'),
    path('contect', views.contactus,name='contect'),
    path('search',views.fetchdata,name='search'),

]

Weth_Ne/urls.py
from django.urls import path
from . import views


app_name='weather'
urlpatterns = [
    path('weather', views.weather,name="w"),

]

account/urls.py
from django.urls import path
from . import views
app_name='account'
urlpatterns = [
    path('register', views.register, name="register"),
    path('login',views.login, name="login"),
    path('logout',views.logout,name='logout')


]

TravelBook/models.py
from django.db import models
from datetime import datetime,date


class Destination(models.Model):
    name = models.CharField(max_length=50)
    img = models.ImageField(upload_to='pics')
    des = models.TextField()
    price = models.IntegerField(default=0)
    offer = models.BooleanField(default=False)
    start=models.DateField(blank=True,null=True)
    end = models.DateField(blank=True, null=True)

    def __str__(self):

        return self.name

Weth_Ne/models.py
from django.db import models

class City(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'cities'

account/models.py
from django.db import models

# Create your models here.

Weth_Ne/forms.py
from django.forms import ModelForm, TextInput
from .models import City 

class CityForm(ModelForm):
    class Meta:
        model = City 
        fields = ['name']
        widgets = {'name' : TextInput(attrs={'class' : 'input', 'placeholder' : 'City Name'})}

TravelBook/views.py
from django.shortcuts import render
from .models import Destination
from django.contrib import messages
from django.core.mail import send_mail
def index(request):

    dests=Destination.objects.all()
    return render(request,'index.html',{'dests':dests})

#suchen
def fetchdata(request) :

    data=Destination.objects.all()
    if request.method == 'POST':
        srh=Destination.objects.filter(name__iexact=request.POST['City'] ,
                                       start=request.POST['Departure'],
                                       end=request.POST['Arrival'],
                                       price=request.POST['Budget'],
                                       )

        cnt={'srh':srh}
        if not srh :
            messages.info(request, 'no resault found ')


    return render(request,'news.html',cnt)




def contactus(request):
    if request.method=='POST' :
        name=request.POST['name']
        email=request.POST['email']
        subject=request.POST['subject']
        message=request.POST['message']
        #'send from ' +" "+name+ "\n" +message
        message1 = "{} from {}".format(message,name)



        send_mail(subject,message1,email,['zaher.abb12@gmail.com'],fail_silently=False)

        return render(request,'contact.html',{'name':name})

    return render(request,'contact.html')



# def newsletter(request):
#     if request.POST =='POST':
#         pass
#     return

Weth_Ne/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
import requests
import datetime
from django.contrib import messages
import os

def weather(request):
    if request.method == 'POST':
    city2 = request.POST['weather']
    context = ""
    url = f'https://api.openweathermap.org/data/2.5/weather?appid={your_key}&q={city2}'
    url_checker = requests.get(url)
    if url_checker.status_code == 200:
        r = requests.get(url).json()
        city_weather = {
            'city': city2,
            'temp': int(r['main']['temp']) - 272,
            'des': r['weather'][0]['main'],
            'description': r['weather'][0]['description'],
            'icon': r['weather'][0]['icon'],
            'min': int(r['main']['temp_min']) - 272,
            'max': int(r['main']['temp_max']) - 272,
            'feels': int(r['main']['feels_like']) - 272,
            'wind': r['wind']['speed'],
            'pressure': r['main']['pressure'],
            'country': r['sys']['country'],
        }
        context = {'city_weather': city_weather}
        return render(request, 'weather_final.html', context)
    else:
        messages.info(request, 'city is not found')
        return redirect('weather:w')

    location_url = 'https://ipinfo.io/'
    location_data = requests.get(location_url).json()
    city2 = location_data['city']
    url = f'https://api.openweathermap.org/data/2.5/weather?appid={your_key}&q={city2}'
    r = requests.get(url).json()

    city_weather = {
        'city': city2,
        'temp': int(r['main']['temp']) - 272,
        'des': r['weather'][0]['main'],
        'description': r['weather'][0]['description'],
        'icon': r['weather'][0]['icon'],
        'min': int(r['main']['temp_min']) - 272,
        'max': int(r['main']['temp_max']) - 272,
        'feels': int(r['main']['feels_like']) - 272,
        'wind': r['wind']['speed'],
        'pressure': r['main']['pressure'],
        'country': r['sys']['country'],
    }
    context = {'city_weather': city_weather}
    return render(request, 'weather_final.html', context)

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth
from django.contrib import messages



def register(request):

    if request.method=='POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        re_password= request.POST['re_password']
        if password==re_password :
            if User.objects.filter(username=username).exists() :
               messages.info(request,'Username is Taken')
               return redirect('account:register')
            elif(User.objects.filter(email=email).exists()):
               messages.info(request,"Email is already Taken")
               return redirect('account:register')
            else:
              user=User.objects.create_user(username=username,password=password,email=email,first_name=first_name,last_name=last_name)
              user.save()
        else:
            messages.info(request, 'password not matched')
            return redirect('account:register')
        return redirect('account:login')
    else:
        return render(request, 'register.html')

def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('Booking:index')
        else :
            messages.info(request,"invaliad login")
            return redirect('account:login')
    return render(request,'login.html')




def logout(request):

    auth.logout(request)
    return render(request,'index.html')

templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Contact</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Travello template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/contact.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/contact_responsive.css' %}">
</head>
<body>

<div class="super_container">

	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
			            	<div class="logo"><a href="{% url 'Booking:index'%}">Travel20</a></div>
							<nav class="main_nav">
								<ul class="d-flex flex-row align-items-start justify-content-start">
									<li class="active"><a href="{% url 'Booking:index'%}"> Home</a></li>
                                    {% if user.is_authenticated %}
									<li><a href="{% url 'weather:w'%}">Weather</a></li>
									<li><a href="{% url 'Booking:contect'%}">Contact</a></li>
								</ul>
							</nav>
							<div class="header_phone ml-auto">Hello,{{user.first_name}}</div>
                                         <li><a href="{% url 'account:logout'%}">logout</a></li>
                                     {% else %}
                                    <li><a href="{% url 'account:register'%}">Register</a></li>
                                    <li><a href="{% url 'account:login'%}">login</a></li>
    								<li><a href={% url 'weather:w'%}>Weather</a></li>
									<li><a href="{% url 'Booking:contect'%}">Contact</a></li>
                                     </ul>
                             </nav>
                                   <div class="header_phone ml-auto">Call us: 00-56 445 678 33</div>
                                    {% endif %}
							<!-- Hamburger -->

							<div class="hamburger ml-auto">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header_social d-flex flex-row align-items-center justify-content-start">
			<ul class="d-flex flex-row align-items-start justify-content-start">
				<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</header>

	<!-- Menu -->

	<div class="menu">
		<div class="menu_header d-flex flex-row align-items-center justify-content-start">
			<div class="menu_logo"><a href="index.html">Travello</a></div>
			<div class="menu_close_container ml-auto"><div class="menu_close"><div></div><div></div></div></div>
		</div>
		<div class="menu_content">
			<ul>
			 <li class="active"><a href="{% url 'Booking:index'%}"> Home</a></li>
                                    {% if user.is_authenticated %}
									<li><a href="{% url 'weather:w'%}">Weather</a></li>
									<li><a href="{% url 'Booking:contect'%}">Contact</a></li>
								</ul>
							</nav>
							<div class="header_phone ml-auto">Hello,{{user.first_name}}</div>
                                         <li><a href="{% url 'account:logout'%}">logout</a></li>
                                     {% else %}
                                    <li><a href="{% url 'account:register'%}">Register</a></li>
                                    <li><a href="{% url 'account:login'%}">login</a></li>
    								<li><a href={% url 'weather:w'%}>Weather</a></li>
									<li><a href="{% url 'Booking:contect'%}">Contact</a></li>
                                     
			</ul>
			{% endif %}
		</div>
		<div class="menu_social">
			<div class="menu_phone ml-auto">Call us: 00-56 445 678 33</div>
			<ul class="d-flex flex-row align-items-start justify-content-start">
				<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</div>
	
	<!-- Home -->

	<div class="home">
		<div class="background_image" style="background-image:url({% static '/images/contact.jpg' %} )"></div>
	</div>

	<!-- Search -->

	<div class="home_search">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="home_search_container">
						<div class="home_search_title">Search for your trip</div>
						<div class="home_search_content">
							<form action="search" method="POST"  class="home_search_form" id="home_search_form">
                                {% csrf_token %}
								<div class="d-flex flex-lg-row flex-column align-items-start justify-content-lg-between justify-content-start">
									<input type="text" class="search_input search_input_1" placeholder="City" name="City" required="required">
									<input type="date" class="search_input search_input_2" placeholder="Departure" name="Departure" required="required">
									<input type="date" class="search_input search_input_3" placeholder="Arrival" name="Arrival" required="required">
									<input type="text" class="search_input search_input_4" placeholder="Budget" name="Budget" required="required">
									<button class="home_search_button">search</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Contact -->
{% if name %}
<div style="color: #00b89c;font-family:'Times New Roman' ">

    <center>
    <h1>Thanks {{ name }} !</h1>
        <p style="color: #0f81cc ; font-size: 40px; font-family:Arial;">  we received you email and will respond shortly  </p>
</center>
</div>
{% else %}
	<div class="contact">
		<div class="container">
			<div class="row">
				<!-- Get in touch -->
				<div class="col-lg-6">
					<div class="contact_content">
						<div class="contact_title">Get in touch with us</div>
						<div class="contact_text">
							<p>Pellentesque sit amet elementum ccumsan sit amet mattis eget, tristique at leo. Vivamus massa.Tempor massa et laoreet. Pellentesque sit amet elementum ccumsan sit amet mattis eget, tristique at leo. Vivamus massa.</p>
						</div>
						<div class="contact_list">
							<ul>
								<li>
									<div>address:</div>
									<div>1481 Creekside Lane Avila Beach, CA 931</div>
								</li>
								<li>
									<div>phone:</div>
									<div>+53 345 7953 32453</div>
								</li>
								<li>
									<div>email:</div>
									<div>yourmail@gmail.com</div>
								</li>
							</ul>
						</div>
					</div>
				</div>

				<!-- Contact Form -->
				<div class="col-lg-6">
					<div class="contact_form_container">
						<form action="contect" method="POST" id="contact_form" class="contact_form">
                            {% csrf_token %}
							<div style="margin-bottom: 18px">
                                <input type="text" class="contact_input contact_input_name inpt" placeholder="Your Name"name="name" required="required"><div class="input_border"></div></div>
							<div class="row">
								<div class="col-lg-6" style="margin-bottom: 18px">
									<div><input type="text" class="contact_input contact_input_email inpt" placeholder="Your E-mail" name="email" required="required"><div class="input_border"></div></div>
								</div>
								<div class="col-lg-6" style="margin-bottom: 18px">
									<div><input type="text" class="contact_input contact_input_subject inpt" placeholder="Subject" name="subject" required="required"><div class="input_border"></div></div>
								</div>
							</div>
							<div><textarea class="contact_textarea contact_input inpt" placeholder="Message" name="message" required="required"></textarea><div class="input_border" style="bottom:3px"></div></div>
							<button class="contact_button">send</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endif %}

	<!-- Map -->

	<div class="contact_map">
		<!-- Google Map -->
		<div class="map">
			<div id="google_map" class="google_map">
				<div class="map_container">
					<div id="map"></div>
				</div>
			</div>
		</div>
	</div>

	<!-- Footer -->

	<footer class="footer">
		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static '/images/footer_1.jpg' %}" data-speed="0.8"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="newsletter">
						<div class="newsletter_title_container text-center">
							<div class="newsletter_title">Subscribe to our newsletter to get the latest trends & news</div>
							<div class="newsletter_subtitle">Join our database NOW!</div>
						</div>
						<div class="newsletter_form_container">
							<form action="#" class="newsletter_form d-flex flex-md-row flex-column align-items-start justify-content-between" id="newsletter_form">
								<div class="d-flex flex-md-row flex-column align-items-start justify-content-between">
									<div><input type="text" class="newsletter_input newsletter_input_name inpt" id="newsletter_input_name" placeholder="Name" required="required"><div class="input_border"></div></div>
									<div><input type="email" class="newsletter_input newsletter_input_email inpt" id="newsletter_input_email" placeholder="Your e-mail" required="required"><div class="input_border"></div></div>
								</div>
								<div><button class="newsletter_button">subscribe</button></div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<div class="row footer_contact_row">
				<div class="col-xl-10 offset-xl-1">
					<div class="row">

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static '/images/sign.svg' %} " alt=""></div>
								<div class="footer_contact_title">give us a call</div>
								<div class="footer_contact_list">
									<ul>
										<li>Office Landline: +44 5567 32 664 567</li>
										<li>Mobile: +44 5567 89 3322 332</li>
									</ul>
								</div>
							</div>
						</div>

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static '/images/trekking.svg' %} " alt=""></div>
								<div class="footer_contact_title">come & drop by</div>
								<div class="footer_contact_list">
									<ul style="max-width:190px">
										<li>4124 Barnes Street, Sanford, FL 32771</li>
									</ul>
								</div>
							</div>
						</div>

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">
								<div class="footer_contact_icon"><img src="{% static '/images/around.svg' %} " alt=""></div>
								<div class="footer_contact_title">send us a message</div>
								<div class="footer_contact_list">
									<ul>
										<li>youremail@gmail.com</li>
										<li>Office@yourbusinessname.com</li>
									</ul>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<div class="col text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --> </div>
	</footer>
</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCIwF204lFZg1y4kPSIhKaHEXMLYxxuMhA' %}"></script>
<script src="{% static 'js/contact.js' %}"></script>
</body>
</html>